# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6c6cf7d85d236f46fd8a1614b7ed36a2303902cb9bedbfcb2815ffb1c85b46da0ac87644389d566f8f27fdfc40f910930456f44b2b53848870bed18da2f5aed

test:
  secret_key_base: e59f99270c14c7487ec34444a88b699b6f1ec1fb8243ffdfae08faaa7e558d0dde6b4e8dcac27e7054786a317af71b8ff27c2946e3fbe36a89584202a444903d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
